# conda env create -f dev-environment.yml
name: pytao-dev
channels:
  - conda-forge
dependencies:
  - python >=3.10
  - bmad >=20260311
  - bokeh
  - h5py
  - httpcore >=1.0.9 # addresses a typing issue when launching jupyter lab
  - ipywidgets
  - jupyterlab>3
  - matplotlib
  - numpy
  - numpydoc
  - openPMD-beamphysics
  - orjson
  # conda-based install pending macos arm64 availability: https://github.com/conda-forge/ormsgpack-feedstock/pull/20
  # - ormsgpack
  - pydantic >=2
  - tqdm
  # Developer
  - mkdocs
  - mkdocs-jupyter
  - mkdocs-material
  - mkdocstrings
  - mkdocstrings-python
  - pygments
  - pytest
  - pytest-cov
  - pip
  - pip:
      - ormsgpack >=1.12.2
