# conda env create -f environment.yml
name: pytao
channels:
  - conda-forge
dependencies:
  - python >=3.10
  - ipykernel
  - ipywidgets
  - jupyterlab
  - bmad >=20260309
  - openPMD-beamphysics
  - numpy
  - orjson
  - h5py
  - pexpect
  - pydantic >=2
  - tqdm
  - pip
