# conda env create -f environment.yml
name: pytao
channels:
  - conda-forge
dependencies:
  - python >=3.10
  - bmad >=20260311
  - h5py
  - httpcore >=1.0.9 # addresses a typing issue when launching jupyter lab
  - ipykernel
  - ipywidgets
  - jupyterlab
  - numpy
  - openPMD-beamphysics >=0.14.1
  - orjson
  # conda-based install pending macos arm64 availability: https://github.com/conda-forge/ormsgpack-feedstock/pull/20
  # - ormsgpack
  - pydantic >=2
  - tqdm
  - pip
  - pip:
      - ormsgpack >=1.12.2
