# conda env create -f environment.yml
name: pytao
channels:
  - conda-forge
dependencies:
  - python >=3.10
  - bmad >=20260309
  - h5py
  - httpcore >=1.0.9 # addresses a typing issue when launching jupyter lab
  - ipykernel
  - ipywidgets
  - jupyterlab
  - numpy
  - openPMD-beamphysics
  - orjson
  - pydantic >=2
  - tqdm
  - pip
