lattices:
  lat_a:
    lattice_file: lattices/lat_a.lat.bmad
  lat_b:
    lattice_file: lattices/lat_b.lat.bmad

tests:
  - type: PairMatch
    description: lat_a[END] matches lat_b[BEGINNING]
    lattice_a_id: lat_a
    element_a: END
    lattice_b_id: lat_b
    element_b: BEGINNING
