lattices:
  lat_a:
    lattice_file: lattices/lat_a.lat.bmad
  lat_b:
    lattice_file: lattices/lat_b.lat.bmad
  lat_c:
    lattice_file: lattices/lat_c.lat.bmad

pair_equality:
  - lattice_a_id: lat_a
    element_a: END
    lattice_b_id: lat_b
    element_b: BEGINNING

  - lattice_a_id: lat_a
    element_a: END
    lattice_b_id: lat_c
    element_b: BEGINNING
    comparison:
      twiss_a_test:
        type: bmag
        max_bmag: 1.05
      floor_x_test:
        atol: 1e-6
      floor_y_test:
        atol: 1e-6
      floor_z_test:
        atol: 1e-6
