from __future__ import annotations

import datetime
import logging
from typing import Any  # noqa: F401

import numpy as np  # noqa: F401

from .core import TaoCore
from .util.parser_types import (  # noqa: F401
    BuildingWallGlobalInfo,
    BuildingWallGraphInfo,
    BuildingWallInfo,
    ConstraintDataInfo,
    ConstraintVarInfo,
    DataD1ArrayInfo,
    DataDArrayInfo,
    DataParameterLineInfo,
    EleChamberWallInfo,
    EleGenGradMapDerivInfo,
    EleGridFieldPointInfo,
    EleLordSlaveInfo,
    EleSpinTaylorInfo,
    EmFieldResult,
    EnumInfo,
    FloorOrbitInfo,
    FloorPlanElementInfo,
    LatBranchListInfo,
    LordControlInfo,
    MatrixResult,
    PlaceBufferInfo,
    PlotLatLayoutInfo,
    PlotLineInfo,
    PlotListRegionInfo,
    PlotSymbolInfo,
    ShapeListInfo,
    ShapePatternNameInfo,
    ShapePatternPointInfo,
    SlaveControlInfo,
    SpinInvariantInfo,
    VarGeneralInfo,
    VarSlaveInfo,
    VarVArrayLineResult,
    VarV1ArrayDataInfo,
)

logger = logging.getLogger(__name__)


class _TaoAutogeneratedCommandMixin(TaoCore):
    _min_tao_version = datetime.datetime(2026, 4, 20)
