from __future__ import annotations

import datetime
import logging

from .core import TaoCore

logger = logging.getLogger(__name__)


class _TaoAutogeneratedCommandMixin(TaoCore):
    _min_tao_version = datetime.datetime(2026, 3, 16)
